refactor(lanelet2_map_validator): move headers to include/
autowarefoundation/autoware_tools pull request #144
Opened 2024-11-05 09:06 UTC by soblin

## Description

move header files to `include`/

## Related links

## Tests performed

## Notes for reviewers

## Interface changes

## Effects on system behavior

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-11-05 23:36 UTC, TaikiYamada4 requested changes
The refactoring regarding the include files seems good, but let me point out two things about the `validation.cpp` related stuff.

2024-11-06 02:16 UTC, soblin commented on map/autoware_lanelet2_map_validator/src/common/validation.cpp
> +  return nullptr;
Okay, but it is valid/normal that the user does not provide the projector information?

2024-11-06 02:28 UTC, TaikiYamada4 commented on map/autoware_lanelet2_map_validator/src/common/validation.cpp
> +  return nullptr;
Hmm..., I guess most users use MGRS so I thought setting it as default is not bad.
However, letting the users notice what projection they're using also feels nice.

I'm OK with making the `--projection` argument mandatory, but if that's the case, please change it like this or it just returns a segmentation fault.
```suggestion
  throw std::invalid_argument("No map projection type specified!");
```

2024-11-06 02:42 UTC, soblin commented on map/autoware_lanelet2_map_validator/src/common/validation.cpp
> +  return nullptr;
I added nullptr check for projector/map and add error string in such cases.

2024-11-06 02:43 UTC, soblin commented on map/autoware_lanelet2_map_validator/src/main.cpp
> +          validator_config.command_line_config.validationConfig);
I added a function `replace_validator` that return a new ValidatonConfig object with a specified validator and rest of the elements as is.

2024-11-06 02:44 UTC, soblin commented on map/autoware_lanelet2_map_validator/src/common/validation.cpp
> -  appendIssues(issues, lanelet::validation::validateMap(*map, val_config));
I moved this to try block because map was not nullptr checked.

2024-11-06 06:14 UTC, TaikiYamada4 reviewed
@soblin 
I realized that we should keep the `include` directory *inside* the `src` directory to follow the coding guidelines, unless we want to export the hpp files as libraries for others.
https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/#not-exporting-headers

Could you replace them please? You can also remove the `lanelet2_map_validator` layer this way.

2024-11-06 08:47 UTC, TaikiYamada4 approved these changes
@soblin 
Thanks for your revision!!
LGTM :+1:

2024-11-06 09:11 UTC, merged