refactor(lalenet2_map_validator): divide map loading process
autowarefoundation/autoware_tools pull request #153
Opened 2024-11-18 13:05 UTC by soblin

## Description

Current implementation tries to load the lanelet_map for each validation process which is inefficient and contaminates the report. With this PR, the map is loaded at first and then passed to each validation process. 

## Related links

## Tests performed

unit test passes

## Notes for reviewers

## Interface changes

None

## Effects on system behavior

None

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [X] The PR follows the [pull request guidelines].
- [X] The PR has been properly tested.
- [X] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [X] There are no open discussions or they are tracked via tickets.
- [X] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-11-19 07:11 UTC, TaikiYamada4 requested changes
I have three review points and two of them are critical when processing the prerequisites.

2024-11-20 03:38 UTC, soblin commented on map/autoware_lanelet2_map_validator/src/common/validation.cpp
> +    const auto prerequisite_issues = check_prerequisite_completion(validators, validator_name);
I added them to `total_issues` in 5d8f6d3e4cec36739c7406e9e2515abe1bad6d07

2024-11-20 03:38 UTC, soblin commented on map/autoware_lanelet2_map_validator/src/common/validation.cpp
> +      prerequisite_issues.empty()
I fixed and added comment on it 5d8f6d3e4cec36739c7406e9e2515abe1bad6d07

2024-11-20 03:38 UTC, soblin commented on map/autoware_lanelet2_map_validator/src/include/lanelet2_map_validator/utils.hpp
> +  if constexpr (std::is_rvalue_reference<decltype(from)>::value) {
I fixed `appendIssue` to take universal reference of `from` to optimize the copy.

The trailing return type denotes the type constraint (concept) that `T` and `std::vector<T>::value_type` matches

2024-11-20 06:37 UTC, TaikiYamada4 approved these changes
I confirmed that `colcon test` passed, invalid arguments are detected correctly, and normal map validation against sample map works correctly. :+1:
(Though I prefer `loadAndValidateMap` rather than `validateMapLoad` but it's your choice)

2024-11-20 06:38 UTC, TaikiYamada4 commented
@soblin 
And please resolve the conflicts around namespaces.

2024-11-20 08:21 UTC, merged